dirDatabase = "data"
databaseUser = f"{dirDatabase}/User.db"
databaseBusiness = f"{dirDatabase}/Business.db"
databaseMain = f"{dirDatabase}/Main.db"

dirImg = "design/img"
imgUser = f"{dirImg}/user.png"
imgPeople = f"{dirImg}/people.png"
imgSetting = f"{dirImg}/setting.png"
imgLogo = f"{dirImg}/logo.png"
imgLogin = f"{dirImg}/login.png"
imgBackGround = f"{dirImg}/background.png"

dirIcon = "design/icon"
iconIcon = f"{dirIcon}/icon.ico"