path = "//192.168.0.123/4. 화재안전팀/00. 공정 및 시간관리/Data"
path_user = f"{path}/User.db"
path_business = f"{path}/Business.db"
path_main = f"{path}/Main.db"

user = "Design/img/user.png"
people = "Design/img/people.png"
setting = "Design/img/setting.png"
logo = "Design/img/logo.png"
icon = "Design/img/icon.ico"
login = "Design/img/login.png"
caution = "Design/img/caution.png"
